### PR TITLE
Create addo

### PR DESCRIPTION
**Pull request by IonutSteff**

### CODE REVIEW

**Comment by JasonTheKitten** [comment]
I'm not exactly sure what this PR does?

**Comment by JasonTheKitten** [comment]
Oh, is this some sort of alternate to radio? I'll check it out later today.

**Comment by JasonTheKitten** [comment]
Ok, I checked this out
I will soon be merging this commit, but I will need to write additional code to actually get this to work

**Comment by ghost** [comment]
Hey, I'm TheNaadamTeam from the  Discord4j Discord server, did you scan the link for viruses on virustotal, or open a virtual browser to test it out?

**Comment by JasonTheKitten** [comment]
Sorry but we decided this PR is too sketchy

**Pull request closed without merging**
